I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    play music 123
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
TypeError: 'int' object is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    play music 123
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "D:\renpy-8.1.3-sdk\renpy\audio\music.py", line 133, in play
    c.enqueue(filenames, loop=loop, synchro_start=synchro_start, fadein=fadein, tight=tight, loop_only=loop_only, relative_volume=relative_volume)
  File "D:\renpy-8.1.3-sdk\renpy\audio\audio.py", line 675, in enqueue
    for filename in filenames:
TypeError: 'int' object is not iterable

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
About Faces 1.0
Sun Oct 15 01:35:59 2023
